// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

/**
 * Build metadata constants for AdvantageKit logging.
 *
 * <p>These values are recorded as metadata in log files to identify builds.
 * In the future, these can be auto-generated by the AdvantageKit gradle plugin.
 */
public final class BuildConstants {
  /** Git commit SHA of the build. */
  public static final String GIT_SHA = "development";

  /** Date when this build was created. */
  public static final String BUILD_DATE = "unknown";

  private BuildConstants() {
    // Utility class - do not instantiate
  }
}
